# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - /charts/adguard
      - /charts/cert-manager-dns-lexicon-webhook
      - /charts/homepage
      - /charts/ntfy
    schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00"
    assignees:
      - GagaMen
  - package-ecosystem: "helm"
    directories:
      - /charts/longhorn
    schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00"
    assignees:
      - GagaMen
