apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.{{ .Values.groupName }}
  labels:
    app: {{ include "cert-manager-dns-lexicon-webhook.name" . }}
    chart: {{ include "cert-manager-dns-lexicon-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ include "cert-manager-dns-lexicon-webhook.namespace" . }}/{{ include "cert-manager-dns-lexicon-webhook.servingCertificate" . }}"
spec:
  group: {{ .Values.groupName }}
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: {{ include "cert-manager-dns-lexicon-webhook.fullname" . }}
    namespace: {{ include "cert-manager-dns-lexicon-webhook.namespace" . }}
  version: v1alpha1
