apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homepage.serviceAccountName" . }}
  namespace: {{ include "homepage.namespace" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
secrets:
  - name: {{ include "homepage.fullname" . }}
